try:
 
    result = some_function()
except SomeException:

    handle_exception()
finally:

    cleanup()
